### ISSUE TITLE
Infinite loop on project component

### ISSUE THREAD

**Issue by AaronShawnSoler** [Lambda-School-Labs/mission-control-fe#240] opened 2020-03-09 17:25 UTC
To our surprise, we discovered an infinite loop on the project component. As we dove deeper to understand this component we noticed an absurd amount of rerenders and infinite loop. This was a preexisting issue from a previous lab team. We cannot seem to find the source of the problem but we know it's coming from the queries as it stops only when the quires are commented out.

**Comment by BryanKAdams** [comment] 2020-03-09 18:17
Setting privatePerm to Null (privatePerm: null) inside NoteFeed/Index.jsx stops the infinite loop.

**Comment by BryanKAdams** [comment] 2020-03-09 18:21
Replacing NoteFeed/Index.jsx to its initial state before Labs21, there aren't any infinite loop issues so I believe the issue arose after changes we've made to the codebase and did not exist before Labs21.

**Comment by RobertDGordon** [comment] 2020-03-11 01:19
Issue was caused by `id` missing on gql queries in the `projectQueries` file, specifically `NOTE_FEED_QUERY`.  I've went through and checked other queries to add id to every point.

Pull request #246 will fix this once merged.

**Comment by BryanKAdams** [comment] 2020-03-18 18:06
This issue was resolved a few merges ago! No more infinite loop :)

**Closed as completed by BryanKAdams** 2020-03-18 18:06 UTC
